### PR TITLE
Added an updated Java auth library

### PR DESCRIPTION
**Pull request by msneddon**
This is a critical fix for https://atlassian.kbase.us/browse/KBASE-2024.

It contains the auth update detailed in this PR:
https://github.com/kbase/auth/pull/14

This is a KBase library, so it does not require any new licensing information.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
Does this just add a new jar?

**Comment by msneddon** [comment]
Yes  I actually think now we should hold off on this PR until kbase/auth#14 is reviewed and accepted, where tests are being discussed.  I don't think any change there would affect this new jar, but just in case let's wait anyway.

**Comment by msneddon** [comment]
The Auth PR was updated to go against the newly created develop branch: https://github.com/kbase/auth/pull/15

**Comment by msneddon** [comment]
kbase/auth#15 was just accepted, so this updated jar can go in now too.

**Comment by kkellerlbl** [comment]
Merging based on KBASE-2024.

**Pull request merged**
