### PR TITLE
Add updated jar for gesellix/unix-socket-factory

### PR DESCRIPTION
**Pull request by bio-boris**
Add an updated jar to avoid error on mac / docker
`Could not initialize class org.newsclub.net.unix.NativeUnixSocket",null,null,1,1]`

I then changed my ant build.xml copy commands to use the `overwrite="true"` directive to suppress the `modifed in the future` warning

### CODE REVIEW

**Comment by kkellerlbl** [comment]
@bio-boris does this PR try to replace a JAR?  I think we try to avoid that in the jars repo.

**Comment by bio-boris** [comment]
@kkellerlbl 
No, this just adds a jar.

**Comment by bio-boris** [comment]
@MrCreosote 
I just added the jar as you suggested I did in Slack. I did not remove any jars
"@Boris you should add the updated jar to github.com/kbase/jars "

**Comment by kkellerlbl** [comment]
Sorry, I was looking at the wrong repo and not paying enough attention.  I can see now the jar isn't in kbase/jars.

Unless there's an objection I'll merge later today.

**Pull request merged**
